### ISSUE TITLE
20K resistor for w/o colon separator circuit

### ISSUE THREAD

**Issue by lstolowski** [elkayem/ESP_NIXIE#2]
Hi @elkayem. ESP_NIXIE is a cool project for me, a newbie :). 
I'making your project with a non-colon separator circuit PCB board. You wrote on the README: "The 20K Ohm resistor is marked as optional. This will illuminate the decimal point between the hours and minutes". It is not clear to me. Did I understand correctly that when I'm using a non-colon separator circuit PCB, I should add a 20K resistor OR the IN-3 tube instead of this resistor?
What about the `#define CLOCK_COLON` line - should it be commented out IF the resistor is there, but if I use the IN-3 I should leave it?
I'll be grateful for your clarifications. Thanks!

**Comment by elkayem** [comment]
It is there if you want the decimal point illuminated. Personally I think it is better to leave it out, even if you don’t have the colon circuit enabled.

**Comment by lstolowski** [comment]
OK I got it. I didn't notice that the decimal point is on the IN14 pin 2 cathode. Thanks. I'm closing it
